SELECT *
FROM Functions
WHERE X = Y
GROUP BY X, Y
HAVING COUNT(*)=2

UNION

SELECT f1.X, f1.Y
FROM Functions AS f1 INNER JOIN Functions AS f2 ON f1.X = f2.Y AND f1.Y = f2.X
WHERE f1.X < f1.Y

ORDER BY X
